### ISSUE TITLE
0.3.0 -> 0.3.1 has breaking changes

### ISSUE THREAD

**Issue by jebrosen** [megumish/r2d2-memcache#13]
`memcache` is a public dependency, so moving it from `0.11` (in `r2d2-memcache 0.3.0`) to `0.13` (in `r2d2-memcache 0.3.1`) is a breaking change and should have been a bump to `0.4.0`.

Would it be possible to get a `0.3.2` release restoring compatibility with `memcache 0.11` , and/or yanking `0.3.1`?

**Comment by aisk** [comment]
Hi, memcache  0.11 and 0.13 shoul be compatible, what issue you got?

**Comment by jebrosen** [comment]
Cargo considers 0.11 and 0.13 to be incompatible with each other because of the version number. This effectively breaks existing crates depending on both `r2d2-memcache 0.3.*` and `memcache 0.11` after a `cargo update`, with errors such as this appearing:

```
   Compiling rocket_contrib v0.5.0-dev (/Users/vsts/agent/2.155.1/work/1/s/contrib/lib)
error[E0271]: type mismatch resolving `<databases::r2d2_memcache::MemcacheConnectionManager as databases::r2d2::ManageConnection>::Connection == databases::memcache::Client`
   --> contrib/lib/src/databases.rs:831:6
    |
831 | impl Poolable for memcache::Client {
    |      ^^^^^^^^ expected struct `databases::r2d2_memcache::memcache::Client`, found struct `databases::memcache::Client`
    |
    = note: expected type `databases::r2d2_memcache::memcache::Client`
               found type `databases::memcache::Client`
note: Perhaps two different versions of crate `memcache` are being used?
   --> contrib/lib/src/databases.rs:831:6
    |
831 | impl Poolable for memcache::Client {
    |      ^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0271`.
error: Could not compile `rocket_contrib`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by aisk** [comment]
Sorry, I did not considered this. I'll release a new version 0.3.2 and restored the memcache dependence.
