### ISSUE TITLE
CI often fails.

### ISSUE THREAD

**Issue by megumish** [megumish/r2d2-memcache#2]
Test 'get' and 'decrement' often fails.I 
It seems that it is a problem that the tests are running in parallel

**Comment by aisk** [comment]
This can be resolved by set the environment variable `RUST_TEST_TASKS` to 1.

**Comment by megumish** [comment]
Thanks. I got it.
I tried it at hand but if I do not set RUST_TEST_THREADS = 1 it will not work well.

**Comment by megumish** [comment]
Fix
